// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qenfivhrinutptlraxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlbmZpdmhyaW51dHB0bHJheGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDg4MzksImV4cCI6MjA3MjA4NDgzOX0.M8jo8DEY6D-_6ryJSMOoY7vuXX9S90PuuMAENUGZYiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});